### ISSUE TITLE
[Enhancement] Specify that times should be in 24-hour format and UTC for manual datetime input

### ISSUE THREAD

**Issue by helpimnotdrowning** [MacielG1/VodRecovery#15]
In the `Vod Recovery` > `Manual Recovery` menu, it asks for the stream start time in semi-ISO format (`yyyy-MM-dd hh:mm:ss`). I've found that it *also* seems to expect a time input in both 24-hour format (which I was already doing, but may not be obvious to 12-hour clock users) and to be in the UTC tz.

The prompt should specify both of these to avoid ambiguity.

Time-sensitive example:
In Vod Recovery > Manual Recovery, enter:
- Name: nekoko88
- Video ID: 41597734903

On [TwitchTracker](https://twitchtracker.com/nekoko88/streams/41597734903), it shows the stream start time in your local timezone, where on [Streamcharts](https://streamscharts.com/channels/nekoko88/streams/41597734903), it shows the time in UTC.

Using the TT start time results in "Unable to get the datetime", while using the Streamcharts start time will successfully find and download the VOD.

**Comment by MacielG1** [comment]
Thanks for pointing that out! I’ll update the prompt in the next update to make it clear that the start time needs to be in 24-hour format and UTC to avoid confusion. By the way, if you're using TwitchTracker to get the datetime, it's better to check the source page since it gives the full datetime on line 8: view-source:https://twitchtracker.com/nekoko88/streams/41597734903
